[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c \"cd backend && poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT\""

[healthcheck]
path = "/health"
initialDelay = 5
timeout = 2
interval = 10
retries = 3
