"""Add educators table

Revision ID: 09bfd1d87bd1
Revises: b4318fbb107a
Create Date: 2025-09-20 11:17:59.216139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bfd1d87bd1'
down_revision = 'b4318fbb107a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('educator', 'super_educator', name='educatorrole'), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('jwt_token', sa.String(length=512), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educators')
    # ### end Alembic commands ###
