"""add kid_absences table and holiday attendance status

Revision ID: 0faed39f155f
Revises: 3009d0ea1444
Create Date: 2025-09-26 11:50:37.414363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0faed39f155f'
down_revision = '3009d0ea1444'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add holiday to attendance_status enum
    op.execute("ALTER TYPE attendance_status ADD VALUE 'holiday'")
    
    op.create_table('kid_absences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('sick', 'holiday', name='absence_reason'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kid_id', 'date', name='uq_kid_absences_kid_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kid_absences')
    # ### end Alembic commands ###
