"""Add users table

Revision ID: 121f02a9665d
Revises: ae406d16f552
Create Date: 2025-09-16 13:37:17.545701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121f02a9665d'
down_revision = 'ae406d16f552'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('parent', 'educator', 'super_educator', name='userrole'), nullable=False),
    sa.Column('jwt_token', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
