"""Fix enum configuration

Revision ID: 132a1c824d7b
Revises: 121f02a9665d
Create Date: 2025-09-16 13:45:53.984912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '132a1c824d7b'
down_revision = '121f02a9665d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('parent', 'educator', 'super_educator', name='userrole'),
               type_=sa.Enum('PARENT', 'EDUCATOR', 'SUPER_EDUCATOR', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('PARENT', 'EDUCATOR', 'SUPER_EDUCATOR', name='userrole', native_enum=False),
               type_=postgresql.ENUM('parent', 'educator', 'super_educator', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
