"""Update DB to use DATABASE_URL

Revision ID: 14d94cc70ad8
Revises: 132a1c824d7b
Create Date: 2025-09-17 13:16:21.499132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d94cc70ad8'
down_revision = '132a1c824d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First create the enum type if it doesn't exist (ignore if already exists)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE userrole AS ENUM ('parent', 'educator', 'super_educator');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Then alter the column with USING clause for proper casting
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('parent', 'educator', 'super_educator', name='userrole'),
               existing_nullable=False,
               postgresql_using='role::userrole')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('parent', 'educator', 'super_educator', name='userrole'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False,
               postgresql_using='role::text')
    
    # Drop the enum type
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
