"""Add groups field to users table

Revision ID: 44326a409bb9
Revises: 14d94cc70ad8
Create Date: 2025-09-19 19:57:11.329961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44326a409bb9'
down_revision = '14d94cc70ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add groups column with proper SQLite/PostgreSQL compatibility
    op.add_column(
        "users",
        sa.Column(
            "groups",
            sa.JSON().with_variant(sa.Text(), "sqlite"), 
            nullable=False,
            server_default="[]"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'groups')
    # ### end Alembic commands ###
