"""Add classes field to users table

Revision ID: 44326a409bb9
Revises: 14d94cc70ad8
Create Date: 2025-09-19 19:57:11.329961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44326a409bb9'
down_revision = '14d94cc70ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('users', sa.Column('_classes_data', sa.Text(), nullable=True))
    
    # Update existing rows with default empty array
    op.execute("UPDATE users SET _classes_data = '[]' WHERE _classes_data IS NULL")
    
    # Make column NOT NULL
    op.alter_column('users', '_classes_data', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_classes_data')
    # ### end Alembic commands ###
