"""Add multi-daycare schema with relationships

Revision ID: 7290bdad5686
Revises: 09bfd1d87bd1
Create Date: 2025-09-20 21:29:49.558843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7290bdad5686'
down_revision = '09bfd1d87bd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daycares',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('daycare_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daycare_id'], ['daycares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_num', sa.String(length=20), nullable=False),
    sa.Column('daycare_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daycare_id'], ['daycares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('educator_groups',
    sa.Column('educator_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['educator_id'], ['educators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE')
    )
    op.create_table('kids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('daycare_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('trusted_adults', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daycare_id'], ['daycares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_kids',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE')
    )
    # Add daycare_id column to educators table
    op.add_column('educators', sa.Column('daycare_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key('fk_educators_daycare_id', 'educators', 'daycares', ['daycare_id'], ['id'], ondelete='CASCADE')
    
    # Rename existing columns to match new schema
    op.alter_column('educators', 'created', new_column_name='created_at')
    op.alter_column('educators', 'updated', new_column_name='updated_at')
    
    # Drop the old group column (replaced by many-to-many relationship)
    op.drop_column('educators', 'group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore educators table to original state
    op.add_column('educators', sa.Column('group', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('educators', 'created_at', new_column_name='created')
    op.alter_column('educators', 'updated_at', new_column_name='updated')
    op.drop_constraint('fk_educators_daycare_id', 'educators', type_='foreignkey')
    op.drop_column('educators', 'daycare_id')
    
    # Drop all new tables
    op.drop_table('parent_kids')
    op.drop_table('kids')
    op.drop_table('educator_groups')
    op.drop_table('parents')
    op.drop_table('groups')
    op.drop_table('daycares')
    # ### end Alembic commands ###
