"""Add users table

Revision ID: ae406d16f552
Revises: 12b8a5095ad5
Create Date: 2025-09-16 13:02:45.223287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae406d16f552'
down_revision = '12b8a5095ad5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
