"""Replace _classes_data with groups

Revision ID: c1d78ecdf23f
Revises: 44326a409bb9
Create Date: 2025-09-19 20:11:47.636330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d78ecdf23f'
down_revision = '44326a409bb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add groups column as nullable first
    op.add_column('users', sa.Column('groups', sa.JSON(), nullable=True))
    
    # Migrate data from _classes_data to groups
    # Convert JSON strings to actual JSON arrays
    op.execute("""
        UPDATE users 
        SET groups = CASE 
            WHEN _classes_data IS NULL OR _classes_data = '' THEN '[]'::json
            ELSE _classes_data::json
        END
    """)
    
    # Make groups column NOT NULL
    op.alter_column('users', 'groups', nullable=False)
    
    # Drop the old _classes_data column
    op.drop_column('users', '_classes_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_classes_data', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'groups')
    # ### end Alembic commands ###
