name: Android CI/CD

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  staging-apk:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Staging APK
        run: ./gradlew assembleStagingDebug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: staging-apk
          path: app/build/outputs/apk/staging/debug/*.apk

  prod-apk:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Production APK
        run: ./gradlew assembleProdRelease
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: prod-apk
          path: app/build/outputs/apk/prod/release/*.apk
